<?php

/**
 * @file
 * Contains duckspot.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;


/**
 * Implements hook_help().
 */
function duckspot_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Help text for the duckspot module.
    case 'help.page.duckspot':
      $output = '';
      $output .= '<h3>' . t('Duckspot module') . '</h3>';
      $output .= '<p>' . t('Enable the module at "/admin/modules".') . '</p>';
      $output .= '<p>' . t('Add spotify credentials at "/admin/config/duckspot/settings"') . '</p>';
      $output .= '<p>' . t('Add & configure the block at "/admin/structure/block"') . '</p>';
      $output .= '<p>' . t('Configure the permissions to view artist pages at "/admin/people/permissions/module/duckspot"') . '</p>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function duckspot_theme()
{
  return [
    'duckspot_block_artists' => [
      'variables' => [
        'body_text' => NULL,
        'artists' => [],
      ],
    ],
    'duckspot_page_artist' => [
      'variables' => [
        'artist' => [],
        'id' => NULL,
      ],
    ],
  ];
}
